title: POCKET ROCKET
email: your-email@domain.com
description: >
  Pocket Rocket is a full-service advertising agency in Manila. Helping you create impactful customer experiences.
url:

# Build settings
markdown: kramdown
theme: minima
gems:

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

prose:
  rooturl: ""
  siteurl: "https://pocketrocketinc.github.io/"
  metadata:
    _data:
      - name: "published"
        field:
          element: 'hidden'
          value: true

      - name: "- id"
        field:
          element: "text"
          label: "id"

      - name: "client"
        field:
          element: "text"
          label: "client"

      - name: "project-title"
        field:
          element: "text"
          label: "project-title"

      - name: "cover-image"
        field:
          element: "text"
          label: "cover-image"
          alterable: true



