title: POCKET ROCKET
email: your-email@domain.com
description: >
  Pocket Rocket is a full-service advertising agency in Manila. Helping you create impactful customer experiences.
url:

# Build settings
markdown: kramdown
theme: minima
gems:

exclude:
  - Gemfile
  - Gemfile.lock
