title: PocketRocketInc
email: your-email@domain.com
description: >
  Pocket Rocket is a full-service advertising agency in Manila. Helping you create impactful customer experiences.
url: "http://www.pocketrocketinc.com/"

# Build settings
markdown: kramdown
theme: minima
gems:

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
