- id: 1
  icon: "https://res.cloudinary.com/pocketrocket/image/upload/v1506343134/misc/store.png"
  service-name: Below the line
  services: "Events. Activations. Promotions. Merchandising. Video Production."

- id: 2
  icon: "https://res.cloudinary.com/pocketrocket/image/upload/v1506343134/misc/monitor.png"
  service-name: Above the line
  services: "Tv. Print. Radio. Out Of Home."

- id: 3
  icon: "https://res.cloudinary.com/pocketrocket/image/upload/v1506343134/misc/digital.png"
  service-name: Digital
  services: "Digital. Social Media. Everything else for a 360-degree customer journey."