- service-name: Below the line
  id: 1
  icon: https://res.cloudinary.com/pocketrocket/image/upload/v1506343134/misc/store.png
  services: Events. Activations.

- service-name: Above the line
  id: 2
  icon: https://res.cloudinary.com/pocketrocket/image/upload/v1506343134/misc/monitor.png
  services: TV. Print. Radio. Out Of Home.

- service-name: Digital
  id: 3
  icon: https://res.cloudinary.com/pocketrocket/image/upload/v1506343134/misc/digital.png
  services: Web. Social Media.
